version: '3'

services:
  fastapi-app:
    build: .
    ports:
      - "8181:8181"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8181 --reload
